apiVersion: v1
kind: ConfigMap
metadata:
  name: metal-enrollment-config
  namespace: metal-enrollment
data:
  DB_DRIVER: "sqlite3"
  ENROLLMENT_URL: "http://enrollment.metal.svc.cluster.local:8080/api/v1/enroll"
  # Update these values for your environment
  BASE_URL: "http://192.168.1.100"
  API_URL: "http://enrollment.metal.svc.cluster.local:8080/api/v1"
